# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_circuitos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(401, 242)
        MainWindow.setMinimumSize(QtCore.QSize(500, 242))
        MainWindow.setMaximumSize(QtCore.QSize(500, 242))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: white;\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 0, 500, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;\n"
                                   "color: black;\n"
                                   "text-align: center;\n"
                                   "")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 160, 101))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("border: none;\n"
                                 "color: black;\n"
                                 "text-align: center;\n"
                                 "")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.lineEdit.setMaxLength(7)
        sizePolicy.setHeightForWidth(
            self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setStyleSheet("border: 2px solid black;\n"
                                    "border-radius: 5px;\n"
                                    "padding: 0px 5px 0px 5px;\n"
                                    "")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton.setAutoDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(
            QtCore.QRect(190, 40, 300, 181))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(
            self.verticalLayoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget_3)
        self.textEdit.setObjectName("textEdit")
        font_textedit = QtGui.QFont()
        font_textedit.setPointSize(8)
        font_textedit.setBold(True)
        font_textedit.setWeight(75)
    
        self.textEdit.setFont(font_textedit)
        self.verticalLayout_4.addWidget(self.textEdit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Circuitos"))
        self.label_2.setText(_translate(
            "MainWindow", "INFORMAÇÕES DE COMARCAS"))
        self.label.setText(_translate("MainWindow", "TAG/CIRCUITO"))
        self.lineEdit.setPlaceholderText(
            _translate("MainWindow", "ex. BBU ou 0465xxx"))
        self.pushButton.setText(_translate("MainWindow", "Buscar"))
        
        self.pushButton.clicked.connect(self.get_circuitos)
        self.lineEdit.returnPressed.connect(self.get_circuitos)
        
    def get_circuitos(self):
        resultado_ip = ''
        resultado_mpls = ''
        nome_gestor = ''
        telefone_local = ''
        telefone_gestor = ''
        nome_cidade = ''
        xcomarca = ''
        tag = self.lineEdit.text().upper()
        
        if (tag != ""):
            with open('circuitos.json') as json_file:
                data = json.load(json_file)
                for i in data:
                    if (i['NOME'].find(tag) != -1 or i['ACESSO'].find(tag) != -1):
                        if (i['NOME'].find('IP') != -1):
                            res = i['ACESSO']
                            nome_cidade = i['CIDADE']
                            resultado_ip = 'CIRCUITO IP - ' + str(res)
                        if (i['NOME'].find('MPLS') != -1):
                            res = i['ACESSO']
                            nome_cidade = i['CIDADE']
                            resultado_mpls = 'CIRCUITO MPLS - ' + str(res)
                with open('telefones.json', encoding="utf8") as json_file2:
                    data2 = json.load(json_file2)
                    for x in data2:
                        if (x['COMARCA'].find(nome_cidade) != -1):
                            xcomarca = x['COMARCA']
                            nome_gestor = x['GESTOR GERAL']
                            telefone_gestor = x['CELULAR']
                            telefone_local = x['TELEFONE COMARCA']
                        

                self.textEdit.setText('Cidade: '+nome_cidade+'\n'+'Gestor: '+nome_gestor+'\n'+'Cel.: '+telefone_gestor+'\n'+'Tel. Local: '+telefone_local+'\n\n'+resultado_ip+'\n'+resultado_mpls+'\n')
                if (resultado_ip+resultado_mpls == ""):
                    self.textEdit.setText('Informação incorreta ou inexistente, tente novamente.')
                    
        else:   self.textEdit.setText('Informação incorreta ou inexistente, tente novamente.')
        
  


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
